### ISSUE TITLE
RESPONSE_BUFFER_SIZE allocating too much memory for http responses

### ISSUE THREAD

**Issue by alexandrezia** [OpenThingsIO/OpenThings-Framework-Firmware-Library#4]
In file `Response.h` line 8,  RESPONSE_BUFFER_SIZE is allocating too much memory for an embedded system 18000 (18k):
```
// The maximum possible size of response messages.
#define RESPONSE_BUFFER_SIZE 18000
```

Opensprinkler is shipping with ESP-12F controller which has too small memory, 80k total which it split with cache, resulting in ~40k for IRAM.
I bought an Opensprinkler which is rebooting randomly due to lack of memory because whenever it receives an http request it is trying to allocate 18k of memory for every response, and it frequently have less than that free due to it's small memory, resulting in random reboots, can't even run a program completely.

In my tests I reduced this #define macro to 8k (8000) and that fixed the memory problem, no more reboots.

A better algorithm should be implemented here in order to allocate less memory, I don't know if 18k is even necessary at all, at least for Opensprinkler it's ok now.

Regards

**Comment by rayshobby** [comment]
The response buffer is allocated and released upon finishing each request. So at most one buffer should exist in memory at any given time. Are you by any chance sending multiple requests at the same time? I wonder if that may cause multiple buffers to exist at the same time. We can't reduce the buffer size because OpenSprinkler and OpenGarage both need this buffer size to accommodate the largest possible response package.

**Comment by alexandrezia** [comment]
I don't know if it is handling concurrent http requests, however one request/buffer is enough to reboot the ESP-12F, it runs with 20k of free memory, sometimes it drops to 14k free memory.
When <18k of free memory happens the next http request triggers a reboot, and that happens every minute or two, one web-browser session is enough to cause a reboot, I was using homeassistant integration and that had worsen this situation.
If 18k buffer is needed, then I think ESP32 will be required instead of ESP-12F.

I even tried a build with more IRAM available, but no success, 
```
build_flags =
     -DPIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48_SECHEAP_SHARED
```

The only solution that fixed the problem was a build with 8k buffer size

I'm running with 8k buffer and it's working as expected, 3 days now without a single reboot, with homeassistant integration 100% online.

If
